server:
  port: 8888
  
  
  
spring:
  cloud:
    config:
      server:
        git:
#          uri: file:D:\\workspace\workspace_boot\usinsaWork\\git-repo
          uri: https://github.com/dsadsaddd1/USINSA.git
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest